### ISSUE TITLE
Secret pass?

### ISSUE THREAD

**Issue by donno2048** [aMoniker/Gush#1]
Is that some kind of secret pass or just a bug?

![image](https://user-images.githubusercontent.com/61805754/131556138-a37fcfec-ace4-4769-850b-90c22b97af53.png)

![image](https://user-images.githubusercontent.com/61805754/131556159-2b17fb4c-53cd-42b2-814e-b46b6510ca64.png)

I would assume it's a secret pass, but this just doesn't look right

![image](https://user-images.githubusercontent.com/61805754/131556348-cc5075cd-c322-462e-93e1-f07cfb2d575e.png)

**Comment by aMoniker** [comment]
That is a secret passage, and should be the only way to exit that level. Maybe that's not a great design.

There's no special handling around rendering the secret walls... they're just missing solid boundaries. It'd be nice to fade the sprite alpha if a player collides with one so you could see them walk through.

The green goo on the walls usually indicates the presence of a secret passage nearby...

**Comment by donno2048** [comment]
Stale
