### ISSUE TITLE
Face the actual direction your facing

### ISSUE THREAD

**Issue by donno2048** [aMoniker/Gush#2]
It would be extremely helpful if the avatar will be facing the direction he attacks and not just right/left.

Anyways this is literally with no exaggeration the best kaboom game I have ever seen.

**Comment by aMoniker** [comment]
Thank you!

The sprites I used only face one direction, and so are only flipped on the x-axis in the game.
If any artists want to draw vertical or diagonal orientations for each sprite, feel free!

**Comment by donno2048** [comment]
Stale
